### ISSUE TITLE
Provide requirements.txt file with module versions

### ISSUE THREAD

**Issue by bazylip** [bcmi/Image-Composition-Assessment-Dataset-CADB#1]
Hi! I would be really thankful if you could provide `requirements.txt` file with versions of modules you used while training and testing the model. This way your code can be reproduced in any moment in the future without any cross-module conflicts due to incompatible versions. Thanks!

**Comment by bo-zhang-cs** [comment]
Thanks for your suggestion and I added ``requirements.txt`` in  the folder ``SAMPNet``.
