### ISSUE TITLE
Model tracing not working

### ISSUE THREAD

**Issue by axmav** [bcmi/Image-Composition-Assessment-Dataset-CADB#3]
Hi @bo-zhang-cs!
I am trying to trace SAMPNet:
```
cfg = Config()
torch_model = SAMPNet(cfg,pretrained=False)
torch_model.eval()
x = torch.randn(2,3,224,224)
s = torch.randn(2,1,224,224)
traced_cell = torch.jit.trace(torch_model, (x, s))
print(traced_cell)
```
At first attempt I got this error:
_TypeError: adaptive_max_pool1d(): argument 'output_size' (position 2) must be tuple of ints, not Tensor_
I fixed it by providing output_size directly as constant output_size=784
Now I get a new error which I don't know how to solve:
```
Traceback (most recent call last):
  File "trace.py", line 38, in <module>
    traced_cell = torch.jit.trace(torch_model, (x, s))
  File "/home/alex/anaconda3/envs/torch/lib/python3.8/site-packages/torch/jit/_trace.py", line 741, in trace
    return trace_module(
  File "/home/alex/anaconda3/envs/torch/lib/python3.8/site-packages/torch/jit/_trace.py", line 958, in trace_module
    module._c._create_method_from_trace(
RuntimeError: 0INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1634272068694/work/torch/csrc/jit/ir/alias_analysis.cpp":584, please report a bug to PyTorch. We don't have an op for aten::fill_ but it isn't a special case.  Argument types: Tensor, bool, 
```
Do you have an idea what the reason is?
Thank you!

**Comment by bo-zhang-cs** [comment]
Hi, Mazorati！As you see, this should be a bug in PyTorch. Maybe you can refer to this [issue](https://github.com/pytorch/pytorch/issues/44469).

**Comment by axmav** [comment]
I reported a [bug](https://github.com/pytorch/pytorch/issues/67834) with more description

**Comment by axmav** [comment]
hey @bo-zhang-cs ! If you are interested I found out that the problem is caused by **SurroundPattern**. A code example is here: https://github.com/pytorch/pytorch/issues/67834#issuecomment-981710251
Actually I still don't know how to fix it.
