### ISSUE TITLE
CPU inference error. Unable to use CPU for inference

### ISSUE THREAD

**Issue by deshwalmahesh** [bcmi/Image-Composition-Assessment-Dataset-CADB#5]
Hi, I have taken a fork of this repo and tried working this with CPU by changing device to CPU wherever possible but it shows some error while creating the net.

1. When the torch module is not compiled with cuda, it'll throw an error
2. When the module is compiled but not used, it'll also throw another error

What can be done to fix this? 

Please see the [modified api.py](https://github.com/deshwalmahesh/Image-Composition-Assessment-Dataset-CADB/blob/main/SAMPNet/api.py) of your code which works with CPU but does not work with CPU. What is missing here?

**Comment by bo-zhang-cs** [comment]
I think this is a problem caused by pytorch and suggest to try different pytorch versions. Besides, it might be more helpful for you to turn to the [github homepage of pytorch](https://github.com/pytorch/pytorch/issues).
