### ISSUE TITLE
Negative value from SAMP weight

### ISSUE THREAD

**Issue by alanlutsen** [bcmi/Image-Composition-Assessment-Dataset-CADB#7]
hello Author,
We are having a hard time reproducing the results of the paper.
More specifically, when running the experiments on the images of Figure 5 we do get weights are negative, and the highest weight is mostly given to the rule of third.

Example for the picture 1 : 
- our score :  [0.5916,  0.3300, -0.4242, -0.0692,  0.1444, -0.3858,  0.3318,  1.6084]
- Figure 5 score : [0.25,  0.13, 0.08, 0.08,  0.07, 0.05,  0.13,  0.21]

We are using the code as given but had to modify it slightly because we are on macOS and cannot use the GPU.
Your help understanding this would be most appreciated.

**Comment by nguyen1872** [comment]
yes, I have same issue. Hope author can reply soon.

**Comment by nguyen187** [comment]
> yes, I have same issue. Hope author can reply soon.

**Comment by bo-zhang-cs** [comment]
Thank you for your interest in our work! Here are the reasons for this phenomenon: 1) The weights we show are normalized among all patterns for a more intuitive explanation, thus there are no negative weights. 2) The model we released is to obtain the same quantitative results in Table 1 and the weights in Figure 5 are obtained by another trained model. To obtain the same results, it is recommended to retrain the model and test.

**Comment by anmolduainter** [comment]
Hi, I am facing the same issue. Can you explain more about whats the difference between current release model and what needs to be trained ?

**Comment by andriyrizhiy** [comment]
any update here?
