### ISSUE TITLE
Getting composition score of a custom test image

### ISSUE THREAD

**Issue by khushboo-anand0909** [bcmi/Image-Composition-Assessment-Dataset-CADB#8]
Thanks for the implementation @bo-zhang-cs , I wish to get a composition score for my custom test image using your pre-trained model. According to my understanding, the pred score obtained in line 77 of test.py can be considered as a score of an image obtained using image and its saliency map. 
https://github.com/bcmi/Image-Composition-Assessment-Dataset-CADB/blob/35c093bafdaaa98923d8ba093a73ddf0079ffbc9/SAMPNet/test.py#L77
Kindly help to clarify this. Thanks.

**Comment by bo-zhang-cs** [comment]
Yes.
